name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build release
        run: dub build -b release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: nvm-passthru.exe
